### ISSUE TITLE
No Freemius links if plugin does not have a settings page

### ISSUE THREAD

**Issue by cliffordp** [Freemius/wordpress-sdk#164]
**Actual Behavior**:
 -  `What is the issue? (*)` No Freemius links if plugin does not have a settings page
 -  `What is the expected behavior?` Account, Contact Us, and wp.org Support Forum links to appear somewhere... the only Freemius-related link that appears is in the plugins.php list of plugins where there's an "Opt Out" link to the left of "Deactivate"

**Versions**: (*)
 -  `Freemius SDK Version:` 1.2.1.7.1
 -  `WordPress Version:` 4.7.5
 -  `PHP Version:` 5.5.24

**Plugin / Theme**: (*)
 -  `Name:` TK SmugMug Slideshow Shortcode
 -  `Slug:` tk-smugmug-slideshow-shortcode
 -  `Freemius ID:` 1072

----
Example code implementation is available at:
* https://wordpress.org/plugins/tk-smugmug-slideshow-shortcode/
* https://github.com/cliffordp/tk-smugmug-slideshow-shortcode/blob/1.5/tk-smugmug-slideshow-shortcode.php#L48-L50

**Comment by jhabdas** [comment]
@cliffordp so it sounds like the sdk necessitates plugins to have a settings page to function? I wonder if there's a way to fake it, and create a faux settings page to trick out the sdk. otherwise any ideas on updating the sdk to provide links when not settings page (my plugin does not use one).

**Comment by cliffordp** [comment]
That's the reason for my bug report. I'm sure @vovafeldman -and-team will fix it in time.

**Comment by jhabdas** [comment]
Thanks. It's open source software so I'm planning to fix it myself. But they need to relax the license before I can. I opened an issue.

**Comment by cliffordp** [comment]
Thanks for logging https://github.com/Freemius/wordpress-sdk/issues/166

**Comment by jhabdas** [comment]
No problem. Info stems from [this investigation](https://github.com/comfusion/hyperdrive/issues/41) on suitability for AGPL for WP.org.

**Comment by gfirem** [comment]
I resolve this creating a menu page to appen direct the account from freemius.  I can share my solution

**Comment by vovafeldman** [comment]
@cliffordp sorry for the late response, for some reason I'm not getting emails from GitHub (will have to fix that). With regards to your question, the pages are actually there, and you can add custom links from wherever you want. You can use:
```php
my_fs()->get_account_url(); // For the Account page.
my_fs()->get_upgrade_url(); // For the pricing page.
my_fs()->contact_url();          // For the contact us page.
```
There's no method for the WP.org support forum link, but you can easily generate that one yourself.

Also, adding them to the plugins.php page under the plugin's links is not a bad idea.

**Comment by jhabdas** [comment]
Awesome! I saw some individuals were trying to workaround this issue. I can't wait to use this service. @cliffordp you'll probably beat me to the punch. Would love to hear how your experience goes using the method described by Vova above.

@vovafeldman If the notifications aren't appearing in your SPAM folder they may be being blocked by a third-party SPAM service and bounced by the email servers. I've witnessed this behavior with Exchange in the recent past, as an example.

**Comment by cliffordp** [comment]
@vovafeldman these 3 return the following:
* http://example.com/wp-admin/admin.php?page=-account
* http://example.com/wp-admin/admin.php?billing_cycle=annual&page=-pricing
* http://example.com/wp-admin/admin.php?page=-contact

Visiting any of these 3 is a WordPress Error:
> Sorry, you are not allowed to access this page.

Other thoughts?

**Comment by toddhalfpenny** [comment]
@cliffordp I've just tested the lastest _develop_ branch and it appears to have been fixed within the last day. Not sure on timings for the next release though.

**Comment by toddhalfpenny** [comment]
Update to this. The fix appears to work if the user has "opted-in", but if not then you are still denied access to the page. On the same test site, after opting-in, the links worked.

**Comment by daniyalahmadk** [comment]
Getting same issue i think it would be good if user could be redirected to "opted-in" page may be? if this error occurs.

**Comment by Jany-M** [comment]
If the plugin is an add-on of another plugin, how do we manage FS urls? specifically opt-in and opt-out?

**Comment by azamat-drewl** [comment]
Still have this issue when Freemius is used in a theme for a multisite network site. If theme does not have a settings page Freemius account links redirect to `Sorry, you are not allowed to access this page` error.

**Comment by azamat-bs** [comment]
Still have this issue when Freemius is used in a theme for a multisite network site. If theme does not have a settings page Freemius account links redirect to `Sorry, you are not allowed to access this page` error.
